version: '3'
services:
  update-spectrum-ip:
    image: cloudflare-spectrum-ddns:dev
    build:
      context: ..
      dockerfile: docker/Dockerfile
    command: 
      - -poll
      - -debug
    env_file: ../.env
    restart: unless-stopped