name: build

on:
  push:
    branches:
      - master
  pull_request:
    branches: 
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: setup
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
    - name: build
      run: go build ./cmd/...
    - name: test
      run: go test -count=1 -v ./...
  release:
    name: release
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: docker-login
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: docker-build-and push
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          file: docker/Dockerfile
          context: .
          push: true
          tags: connormckelvey/cloudflare-spectrum-ddns:latest
